<a href="https://colab.research.google.com/github/rsadithya76-create/AI-Summer-Internship/blob/main/eclat_Data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv('/content/drive/MyDrive/Ai/Market_Basket_Optimisation.csv',header=None)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df.isna().sum()

0        0
1     1754
2     3112
3     4156
4     4972
5     5637
6     6132
7     6520
8     6847
9     7106
10    7245
11    7347
12    7414
13    7454
14    7476
15    7493
16    7497
17    7497
18    7498
19    7500
dtype: int64

In [ ]:
transactions=[]
for i in range(0,len(df)):
  transactions.append(str(df.values[i,j]) for j in range(0,20) if df.values[i,j]!='nan')
transactions

[<generator object <genexpr> at 0x78312ca484a0>,
 <generator object <genexpr> at 0x78312ca48740>,
 <generator object <genexpr> at 0x78312ca48660>,
 <generator object <genexpr> at 0x78312ca48580>,
 <generator object <genexpr> at 0x78312ca48820>,
 <generator object <genexpr> at 0x78312ca48900>,
 <generator object <genexpr> at 0x78312ca489e0>,
 <generator object <genexpr> at 0x78312ca48ac0>,
 <generator object <genexpr> at 0x78312ca48e40>,
 <generator object <genexpr> at 0x78312ca48d60>,
 <generator object <genexpr> at 0x78312ca48f20>,
 <generator object <genexpr> at 0x78312ca48c80>,
 <generator object <genexpr> at 0x78312ca48ba0>,
 <generator object <genexpr> at 0x78312ca49380>,
 <generator object <genexpr> at 0x78312ca491c0>,
 <generator object <genexpr> at 0x78312ca490e0>,
 <generator object <genexpr> at 0x78312ca492a0>,
 <generator object <genexpr> at 0x78312ca49000>,
 <generator object <genexpr> at 0x78312ca49460>,
 <generator object <genexpr> at 0x78312ca49540>,
 <generator object <genexpr> at 0x78312ca49620>,
 <generator object <genexpr> at 0x78312ca49700>,
 <generator object <genexpr> at 0x78312ca497e0>,
 <generator object <genexpr> at 0x78312ca498c0>,
 <generator object <genexpr> at 0x78312ca499a0>,
 <generator object <genexpr> at 0x78312ca49a80>,
 <generator object <genexpr> at 0x78312ca49b60>,
 <generator object <genexpr> at 0x78312ca49c40>,
 <generator object <genexpr> at 0x78312ca49d20>,
 <generator object <genexpr> at 0x78312ca49e00>,
 <generator object <genexpr> at 0x78312ca49ee0>,
 <generator object <genexpr> at 0x78312ca49fc0>,
 <generator object <genexpr> at 0x78312ca4a0a0>,
 <generator object <genexpr> at 0x78312ca4a180>,
 <generator object <genexpr> at 0x78312ca4a260>,
 <generator object <genexpr> at 0x78312ca4a340>,
 <generator object <genexpr> at 0x78312ca4a420>,
 <generator object <genexpr> at 0x78312ca4a500>,
 <generator object <genexpr> at 0x78312ca4a5e0>,
 <generator object <genexpr> at 0x78312ca4a6c0>,
 <generator object <genexpr> at 0x78312ca4a7a0>,
 <generator object <genexpr> at 0x78312ca4a880>,
 <generator object <genexpr> at 0x78312ca4a960>,
 <generator object <genexpr> at 0x78312ca4aa40>,
 <generator object <genexpr> at 0x78312ca4ab20>,
 <generator object <genexpr> at 0x78312ca4ac00>,
 <generator object <genexpr> at 0x78312ca4ace0>,
 <generator object <genexpr> at 0x78312ca4adc0>,
 <generator object <genexpr> at 0x78312ca4aea0>,
 <generator object <genexpr> at 0x78312ca4af80>,
 <generator object <genexpr> at 0x78312ca4b060>,
 <generator object <genexpr> at 0x78312ca4b140>,
 <generator object <genexpr> at 0x78312ca4b220>,
 <generator object <genexpr> at 0x78312ca4b300>,
 <generator object <genexpr> at 0x78312ca4b3e0>,
 <generator object <genexpr> at 0x78312ca4b4c0>,
 <generator object <genexpr> at 0x78312ca4b5a0>,
 <generator object <genexpr> at 0x78312ca4b680>,
 <generator object <genexpr> at 0x78312ca4b760>,
 <generator object <genexpr> at 0x78312ca4b840>,
 <generator object <genexpr> at 0x78312ca4b920>,
 <generator object <genexpr> at 0x78312ca4ba00>,
 <generator object <genexpr> at 0x78312ca4bae0>,
 <generator object <genexpr> at 0x78312ca4bbc0>,
 <generator object <genexpr> at 0x78312ca4bca0>,
 <generator object <genexpr> at 0x78312ca4bd80>,
 <generator object <genexpr> at 0x78312ca4be60>,
 <generator object <genexpr> at 0x78312ca50040>,
 <generator object <genexpr> at 0x78312ca50120>,
 <generator object <genexpr> at 0x78312ca50200>,
 <generator object <genexpr> at 0x78312ca502e0>,
 <generator object <genexpr> at 0x78312ca503c0>,
 <generator object <genexpr> at 0x78312ca504a0>,
 <generator object <genexpr> at 0x78312ca50580>,
 <generator object <genexpr> at 0x78312ca50660>,
 <generator object <genexpr> at 0x78312ca50740>,
 <generator object <genexpr> at 0x78312ca50820>,
 <generator object <genexpr> at 0x78312ca50900>,
 <generator object <genexpr> at 0x78312ca509e0>,
 <generator object <genexpr> at 0x78312ca50ac0>,
 <generator object <genexpr> at 0x78312ca50ba0>,
 <generator object <genexpr> at 0x78312ca50c80>,
 <generator object <genexpr> at 0x78312ca50d60>,
 <generator object <genexpr> at 0x78312ca50e40>,
 <generator object <genexpr> at 0x78312ca50f20>,
 <generator object <genexpr> at 0x78312ca51000>,
 <generator object <genexpr> at 0x78312ca510e0>,
 <generator object <genexpr> at 0x78312ca511c0>,
 <generator object <genexpr> at 0x78312ca512a0>,
 <generator object <genexpr> at 0x78312ca51380>,
 <generator object <genexpr> at 0x78312ca51460>,
 <generator object <genexpr> at 0x78312ca51540>,
 <generator object <genexpr> at 0x78312ca51620>,
 <generator object <genexpr> at 0x78312ca51700>,
 <generator object <genexpr> at 0x78312ca517e0>,
 <generator object <genexpr> at 0x78312ca518c0>,
 <generator object <genexpr> at 0x78312ca519a0>,
 <generator object <genexpr> at 0x78312ca51a80>,
 <generator object <genexpr> at 0x78312ca51b60>,
 <generator object <genexpr> at 0x78312ca51c40>,
 <generator object <genexpr> at 0x78312ca51d20>,
 <generator object <genexpr> at 0x78312ca51e00>,
 <generator object <genexpr> at 0x78312ca51ee0>,
 <generator object <genexpr> at 0x78312ca51fc0>,
 <generator object <genexpr> at 0x78312ca520a0>,
 <generator object <genexpr> at 0x78312ca52180>,
 <generator object <genexpr> at 0x78312ca52260>,
 <generator object <genexpr> at 0x78312ca52340>,
 <generator object <genexpr> at 0x78312ca52420>,
 <generator object <genexpr> at 0x78312ca52500>,
 <generator object <genexpr> at 0x78312ca525e0>,
 <generator object <genexpr> at 0x78312ca526c0>,
 <generator object <genexpr> at 0x78312ca527a0>,
 <generator object <genexpr> at 0x78312ca52880>,
 <generator object <genexpr> at 0x78312ca52960>,
 <generator object <genexpr> at 0x78312ca52a40>,
 <generator object <genexpr> at 0x78312ca52b20>,
 <generator object <genexpr> at 0x78312ca52c00>,
 <generator object <genexpr> at 0x78312ca52ce0>,
 <generator object <genexpr> at 0x78312ca52dc0>,
 <generator object <genexpr> at 0x78312ca52ea0>,
 <generator object <genexpr> at 0x78312ca52f80>,
 <generator object <genexpr> at 0x78312ca53060>,
 <generator object <genexpr> at 0x78312ca53140>,
 <generator object <genexpr> at 0x78312ca53220>,
 <generator object <genexpr> at 0x78312ca53300>,
 <generator object <genexpr> at 0x78312ca533e0>,
 <generator object <genexpr> at 0x78312ca534c0>,
 <generator object <genexpr> at 0x78312ca535a0>,
 <generator object <genexpr> at 0x78312ca53680>,
 <generator object <genexpr> at 0x78312ca53760>,
 <generator object <genexpr> at 0x78312ca53840>,
 <generator object <genexpr> at 0x78312ca53920>,
 <generator object <genexpr> at 0x78312ca53a00>,
 <generator object <genexpr> at 0x78312ca53ae0>,
 <generator object <genexpr> at 0x78312ca53bc0>,
 <generator object <genexpr> at 0x78312ca53ca0>,
 <generator object <genexpr> at 0x78312ca53d80>,
 <generator object <genexpr> at 0x78312ca53e60>,
 <generator object <genexpr> at 0x78312ca58040>,
 <generator object <genexpr> at 0x78312ca58120>,
 <generator object <genexpr> at 0x78312ca58200>,
 <generator object <genexpr> at 0x78312ca582e0>,
 <generator object <genexpr> at 0x78312ca583c0>,
 <generator object <genexpr> at 0x78312ca584a0>,
 <generator object <genexpr> at 0x78312ca58580>,
 <generator object <genexpr> at 0x78312ca58660>,
 <generator object <genexpr> at 0x78312ca58740>,
 <generator object <genexpr> at 0x78312ca58820>,
 <generator object <genexpr> at 0x78312ca58900>,
 <generator object <genexpr> at 0x78312ca589e0>,
 <generator object <genexpr> at 0x78312ca58ac0>,
 <generator object <genexpr> at 0x78312ca58ba0>,
 <generator object <genexpr> at 0x78312ca58c80>,
 <generator object <genexpr> at 0x78312ca58d60>,
 <generator object <genexpr> at 0x78312ca58e40>,
 <generator object <genexpr> at 0x78312ca58f20>,
 <generator object <genexpr> at 0x78312ca59000>,
 <generator object <genexpr> at 0x78312ca590e0>,
 <generator object <genexpr> at 0x78312ca591c0>,
 <generator object <genexpr> at 0x78312ca592a0>,
 <generator object <genexpr> at 0x78312ca59380>,
 <generator object <genexpr> at 0x78312ca59460>,
 <generator object <genexpr> at 0x78312ca59540>,
 <generator object <genexpr> at 0x78312ca59620>,
 <generator object <genexpr> at 0x78312ca59700>,
 <generator object <genexpr> at 0x78312ca597e0>,
 <generator object <genexpr> at 0x78312ca598c0>,
 <generator object <genexpr> at 0x78312ca599a0>,
 <generator object <genexpr> at 0x78312ca59a80>,
 <generator object <genexpr> at 0x78312ca59b60>,
 <generator object <genexpr> at 0x78312ca59c40>,
 <generator object <genexpr> at 0x78312ca59d20>,
 <generator object <genexpr> at 0x78312ca59e00>,
 <generator object <genexpr> at 0x78312ca59ee0>,
 <generator object <genexpr> at 0x78312ca59fc0>,
 <generator object <genexpr> at 0x78312ca5a0a0>,
 <generator object <genexpr> at 0x78312ca5a180>,
 <generator object <genexpr> at 0x78312ca5a260>,
 <generator object <genexpr> at 0x78312ca5a340>,
 <generator object <genexpr> at 0x78312ca5a420>,
 <generator object <genexpr> at 0x78312ca5a500>,
 <generator object <genexpr> at 0x78312ca5a5e0>,
 <generator object <genexpr> at 0x78312ca5a6c0>,
 <generator object <genexpr> at 0x78312ca5a7a0>,
 <generator object <genexpr> at 0x78312ca5a880>,
 <generator object <genexpr> at 0x78312ca5a960>,
 <generator object <genexpr> at 0x78312ca5aa40>,
 <generator object <genexpr> at 0x78312ca5ab20>,
 <generator object <genexpr> at 0x78312ca5ac00>,
 <generator object <genexpr> at 0x78312ca5ace0>,
 <generator object <genexpr> at 0x78312ca5adc0>,
 <generator object <genexpr> at 0x78312ca5aea0>,
 <generator object <genexpr> at 0x78312ca5af80>,
 <generator object <genexpr> at 0x78312ca5b060>,
 <generator object <genexpr> at 0x78312ca5b140>,
 <generator object <genexpr> at 0x78312ca5b220>,
 <generator object <genexpr> at 0x78312ca5b300>,
 <generator object <genexpr> at 0x78312ca5b3e0>,
 <generator object <genexpr> at 0x78312ca5b4c0>,
 <generator object <genexpr> at 0x78312ca5b5a0>,
 <generator object <genexpr> at 0x78312ca5b680>,
 <generator object <genexpr> at 0x78312ca5b760>,
 <generator object <genexpr> at 0x78312ca5b840>,
 <generator object <genexpr> at 0x78312ca5b920>,
 <generator object <genexpr> at 0x78312ca5ba00>,
 <generator object <genexpr> at 0x78312ca5bae0>,
 <generator object <genexpr> at 0x78312ca5bbc0>,
 <generator object <genexpr> at 0x78312ca5bca0>,
 <generator object <genexpr> at 0x78312ca5bd80>,
 <generator object <genexpr> at 0x78312ca5be60>,
 <generator object <genexpr> at 0x78312ca5c040>,
 <generator object <genexpr> at 0x78312ca5c120>,
 <generator object <genexpr> at 0x78312ca5c200>,
 <generator object <genexpr> at 0x78312ca5c2e0>,
 <generator object <genexpr> at 0x78312ca5c3c0>,
 <generator object <genexpr> at 0x78312ca5c4a0>,
 <generator object <genexpr> at 0x78312ca5c580>,
 <generator object <genexpr> at 0x78312ca5c660>,
 <generator object <genexpr> at 0x78312ca5c740>,
 <generator object <genexpr> at 0x78312ca5c820>,
 <generator object <genexpr> at 0x78312ca5c900>,
 <generator object <genexpr> at 0x78312ca5c9e0>,
 <generator object <genexpr> at 0x78312ca5cac0>,
 <generator object <genexpr> at 0x78312ca5cba0>,
 <generator object <genexpr> at 0x78312ca5cc80>,
 <generator object <genexpr> at 0x78312ca5cd60>,
 <generator object <genexpr> at 0x78312ca5ce40>,
 <generator object <genexpr> at 0x78312ca5cf20>,
 <generator object <genexpr> at 0x78312ca5d000>,
 <generator object <genexpr> at 0x78312ca5d0e0>,
 <generator object <genexpr> at 0x78312ca5d1c0>,
 <generator object <genexpr> at 0x78312ca5d2a0>,
 <generator object <genexpr> at 0x78312ca5d380>,
 <generator object <genexpr> at 0x78312ca5d460>,
 <generator object <genexpr> at 0x78312ca5d540>,
 <generator object <genexpr> at 0x78312ca5d620>,
 <generator object <genexpr> at 0x78312ca5d700>,
 <generator object <genexpr> at 0x78312ca5d7e0>,
 <generator object <genexpr> at 0x78312ca5d8c0>,
 <generator object <genexpr> at 0x78312ca5d9a0>,
 <generator object <genexpr> at 0x78312ca5da80>,
 <generator object <genexpr> at 0x78312ca5db60>,
 <generator object <genexpr> at 0x78312ca5dc40>,
 <generator object <genexpr> at 0x78312ca5dd20>,
 <generator object <genexpr> at 0x78312ca5de00>,
 <generator object <genexpr> at 0x78312ca5dee0>,
 <generator object <genexpr> at 0x78312ca5dfc0>,
 <generator object <genexpr> at 0x78312ca5e0a0>,
 <generator object <genexpr> at 0x78312ca5e180>,
 <generator object <genexpr> at 0x78312ca5e260>,
 <generator object <genexpr> at 0x78312ca5e340>,
 <generator object <genexpr> at 0x78312ca5e420>,
 <generator object <genexpr> at 0x78312ca5e500>,
 <generator object <genexpr> at 0x78312ca5e5e0>,
 <generator object <genexpr> at 0x78312ca5e6c0>,
 <generator object <genexpr> at 0x78312ca5e7a0>,
 <generator object <genexpr> at 0x78312ca5e880>,
 <generator object <genexpr> at 0x78312ca5e960>,
 <generator object <genexpr> at 0x78312ca5ea40>,
 <generator object <genexpr> at 0x78312ca5eb20>,
 <generator object <genexpr> at 0x78312ca5ec00>,
 <generator object <genexpr> at 0x78312ca5ece0>,
 <generator object <genexpr> at 0x78312ca5edc0>,
 <generator object <genexpr> at 0x78312ca5eea0>,
 <generator object <genexpr> at 0x78312ca5ef80>,
 <generator object <genexpr> at 0x78312ca5f060>,
 <generator object <genexpr> at 0x78312ca5f140>,
 <generator object <genexpr> at 0x78312ca5f220>,
 <generator object <genexpr> at 0x78312ca5f300>,
 <generator object <genexpr> at 0x78312ca5f3e0>,
 <generator object <genexpr> at 0x78312ca5f4c0>,
 <generator object <genexpr> at 0x78312ca5f5a0>,
 <generator object <genexpr> at 0x78312ca5f680>,
 <generator object <genexpr> at 0x78312ca5f760>,
 <generator object <genexpr> at 0x78312ca5f840>,
 <generator object <genexpr> at 0x78312ca5f920>,
 <generator object <genexpr> at 0x78312ca5fa00>,
 <generator object <genexpr> at 0x78312ca5fae0>,
 <generator object <genexpr> at 0x78312ca5fbc0>,
 <generator object <genexpr> at 0x78312ca5fca0>,
 <generator object <genexpr> at 0x78312ca5fd80>,
 <generator object <genexpr> at 0x78312ca5fe60>,
 <generator object <genexpr> at 0x78312ca64040>,
 <generator object <genexpr> at 0x78312ca64120>,
 <generator object <genexpr> at 0x78312ca64200>,
 <generator object <genexpr> at 0x78312ca642e0>,
 <generator object <genexpr> at 0x78312ca643c0>,
 <generator object <genexpr> at 0x78312ca644a0>,
 <generator object <genexpr> at 0x78312ca64580>,
 <generator object <genexpr> at 0x78312ca64660>,
 <generator object <genexpr> at 0x78312ca64740>,
 <generator object <genexpr> at 0x78312ca64820>,
 <generator object <genexpr> at 0x78312ca64900>,
 <generator object <genexpr> at 0x78312ca649e0>,
 <generator object <genexpr> at 0x78312ca64ac0>,
 <generator object <genexpr> at 0x78312ca64ba0>,
 <generator object <genexpr> at 0x78312ca64c80>,
 <generator object <genexpr> at 0x78312ca64d60>,
 <generator object <genexpr> at 0x78312ca64e40>,
 <generator object <genexpr> at 0x78312ca64f20>,
 <generator object <genexpr> at 0x78312ca65000>,
 <generator object <genexpr> at 0x78312ca650e0>,
 <generator object <genexpr> at 0x78312ca651c0>,
 <generator object <genexpr> at 0x78312ca652a0>,
 <generator object <genexpr> at 0x78312ca65380>,
 <generator object <genexpr> at 0x78312ca65460>,
 <generator object <genexpr> at 0x78312ca65540>,
 <generator object <genexpr> at 0x78312ca65620>,
 <generator object <genexpr> at 0x78312ca65700>,
 <generator object <genexpr> at 0x78312ca657e0>,
 <generator object <genexpr> at 0x78312ca658c0>,
 <generator object <genexpr> at 0x78312ca659a0>,
 <generator object <genexpr> at 0x78312ca65a80>,
 <generator object <genexpr> at 0x78312ca65b60>,
 <generator object <genexpr> at 0x78312ca65c40>,
 <generator object <genexpr> at 0x78312ca65d20>,
 <generator object <genexpr> at 0x78312ca65e00>,
 <generator object <genexpr> at 0x78312ca65ee0>,
 <generator object <genexpr> at 0x78312ca65fc0>,
 <generator object <genexpr> at 0x78312ca660a0>,
 <generator object <genexpr> at 0x78312ca66180>,
 <generator object <genexpr> at 0x78312ca66260>,
 <generator object <genexpr> at 0x78312ca66340>,
 <generator object <genexpr> at 0x78312ca66420>,
 <generator object <genexpr> at 0x78312ca66500>,
 <generator object <genexpr> at 0x78312ca665e0>,
 <generator object <genexpr> at 0x78312ca666c0>,
 <generator object <genexpr> at 0x78312ca667a0>,
 <generator object <genexpr> at 0x78312ca66880>,
 <generator object <genexpr> at 0x78312ca66960>,
 <generator object <genexpr> at 0x78312ca66a40>,
 <generator object <genexpr> at 0x78312ca66b20>,
 <generator object <genexpr> at 0x78312ca66c00>,
 <generator object <genexpr> at 0x78312ca66ce0>,
 <generator object <genexpr> at 0x78312ca66dc0>,
 <generator object <genexpr> at 0x78312ca66ea0>,
 <generator object <genexpr> at 0x78312ca66f80>,
 <generator object <genexpr> at 0x78312ca67060>,
 <generator object <genexpr> at 0x78312ca67140>,
 <generator object <genexpr> at 0x78312ca67220>,
 <generator object <genexpr> at 0x78312ca67300>,
 <generator object <genexpr> at 0x78312ca673e0>,
 <generator object <genexpr> at 0x78312ca674c0>,
 <generator object <genexpr> at 0x78312ca675a0>,
 <generator object <genexpr> at 0x78312ca67680>,
 <generator object <genexpr> at 0x78312ca67760>,
 <generator object <genexpr> at 0x78312ca67840>,
 <generator object <genexpr> at 0x78312ca67920>,
 <generator object <genexpr> at 0x78312ca67a00>,
 <generator object <genexpr> at 0x78312ca67ae0>,
 <generator object <genexpr> at 0x78312ca67bc0>,
 <generator object <genexpr> at 0x78312ca67ca0>,
 <generator object <genexpr> at 0x78312ca67d80>,
 <generator object <genexpr> at 0x78312ca67e60>,
 <generator object <genexpr> at 0x78312ca6c040>,
 <generator object <genexpr> at 0x78312ca6c120>,
 <generator object <genexpr> at 0x78312ca6c200>,
 <generator object <genexpr> at 0x78312ca6c2e0>,
 <generator object <genexpr> at 0x78312ca6c3c0>,
 <generator object <genexpr> at 0x78312ca6c4a0>,
 <generator object <genexpr> at 0x78312ca6c580>,
 <generator object <genexpr> at 0x78312ca6c660>,
 <generator object <genexpr> at 0x78312ca6c740>,
 <generator object <genexpr> at 0x78312ca6c820>,
 <generator object <genexpr> at 0x78312ca6c900>,
 <generator object <genexpr> at 0x78312ca6c9e0>,
 <generator object <genexpr> at 0x78312ca6cac0>,
 <generator object <genexpr> at 0x78312ca6cba0>,
 <generator object <genexpr> at 0x78312ca6cc80>,
 <generator object <genexpr> at 0x78312ca6cd60>,
 <generator object <genexpr> at 0x78312ca6ce40>,
 <generator object <genexpr> at 0x78312ca6cf20>,
 <generator object <genexpr> at 0x78312ca6d000>,
 <generator object <genexpr> at 0x78312ca6d0e0>,
 <generator object <genexpr> at 0x78312ca6d1c0>,
 <generator object <genexpr> at 0x78312ca6d2a0>,
 <generator object <genexpr> at 0x78312ca6d380>,
 <generator object <genexpr> at 0x78312ca6d460>,
 <generator object <genexpr> at 0x78312ca6d540>,
 <generator object <genexpr> at 0x78312ca6d620>,
 <generator object <genexpr> at 0x78312ca6d700>,
 <generator object <genexpr> at 0x78312ca6d7e0>,
 <generator object <genexpr> at 0x78312ca6d8c0>,
 <generator object <genexpr> at 0x78312ca6d9a0>,
 <generator object <genexpr> at 0x78312ca6da80>,
 <generator object <genexpr> at 0x78312ca6db60>,
 <generator object <genexpr> at 0x78312ca6dc40>,
 <generator object <genexpr> at 0x78312ca6dd20>,
 <generator object <genexpr> at 0x78312ca6de00>,
 <generator object <genexpr> at 0x78312ca6dee0>,
 <generator object <genexpr> at 0x78312ca6dfc0>,
 <generator object <genexpr> at 0x78312ca6e0a0>,
 <generator object <genexpr> at 0x78312ca6e180>,
 <generator object <genexpr> at 0x78312ca6e260>,
 <generator object <genexpr> at 0x78312ca6e340>,
 <generator object <genexpr> at 0x78312ca6e420>,
 <generator object <genexpr> at 0x78312ca6e500>,
 <generator object <genexpr> at 0x78312ca6e5e0>,
 <generator object <genexpr> at 0x78312ca6e6c0>,
 <generator object <genexpr> at 0x78312ca6e7a0>,
 <generator object <genexpr> at 0x78312ca6e880>,
 <generator object <genexpr> at 0x78312ca6e960>,
 <generator object <genexpr> at 0x78312ca6ea40>,
 <generator object <genexpr> at 0x78312ca6eb20>,
 <generator object <genexpr> at 0x78312ca6ec00>,
 <generator object <genexpr> at 0x78312ca6ece0>,
 <generator object <genexpr> at 0x78312ca6edc0>,

In [ ]:
from itertools import combinations

item_tidset = {}

for tid, transaction in enumerate(transactions):
    for item in transaction:
        if item not in item_tidset:
            item_tidset[item] = set()
        item_tidset[item].add(tid)

In [ ]:
min_support_count = 20

In [ ]:
frequent_itemsets = []

items = list(item_tidset.keys())

for item1, item2 in combinations(items, 2):

    common_tidset = item_tidset[item1] & item_tidset[item2]

    support_count = len(common_tidset)

    if support_count >= min_support_count:

        frequent_itemsets.append([
            item1,
            item2,
            support_count,
            support_count / len(transactions)
        ])

In [ ]:
df_eclat = pd.DataFrame(
    frequent_itemsets,
    columns=[
        'Item 1',
        'Item 2',
        'Support Count',
        'Support'
    ]
)

df_eclat

            Item 1           Item 2  Support Count  Support
0             eggs  frozen smoothie           7501      1.0
1             eggs      yogurt cake           7501      1.0
2             eggs   low fat yogurt           7501      1.0
3             eggs              nan           7501      1.0
4  frozen smoothie      yogurt cake           7501      1.0
5  frozen smoothie   low fat yogurt           7501      1.0
6  frozen smoothie              nan           7501      1.0
7      yogurt cake   low fat yogurt           7501      1.0
8      yogurt cake              nan           7501      1.0
9   low fat yogurt              nan           7501      1.0

In [ ]:
df_eclat = df_eclat.sort_values(
    by='Support',
    ascending=False
)

print(df_eclat.head(20))

            Item 1           Item 2  Support Count  Support
0             eggs  frozen smoothie           7501      1.0
1             eggs      yogurt cake           7501      1.0
2             eggs   low fat yogurt           7501      1.0
3             eggs              nan           7501      1.0
4  frozen smoothie      yogurt cake           7501      1.0
5  frozen smoothie   low fat yogurt           7501      1.0
6  frozen smoothie              nan           7501      1.0
7      yogurt cake   low fat yogurt           7501      1.0
8      yogurt cake              nan           7501      1.0
9   low fat yogurt              nan           7501      1.0